### ISSUE TITLE
Expected time to earn rewards broken

### ISSUE THREAD

**Issue by ThunderousDreamer** [B3-Coin/B3-CoinV2#37]
Visual bug in 3.1.1.2 QT Windows wallet, expected time to earn rewards has been on 4 seconds for more than 2 days. 

![image](https://user-images.githubusercontent.com/31323882/34542888-5269ee9c-f093-11e7-9b84-f277b2dc73e1.png)

**Comment by Leass** [comment]
Since B3coin uses PoS3 reward mechanism, weight as parameter is not used, hence there is just visual bug showing in user interface.
Since PoS3 stake mechanism in large simplification is based on the depth of input in blockchain, estimated time in fact could not be estimated, so it should be completly removed from UI since it's misleading.
