### ISSUE TITLE
Coins stuck

### ISSUE THREAD

**Issue by robertorange949** [B3-Coin/B3-CoinV2#43]
https://chainz.cryptoid.info/b3/tx.dws?0b9b2d3d7415783e40e8c3f358b86dbafd79f5ee4dba2ecd6bc04fc18b45e0e8.htm

I have 244,000 b3 coins on that I withdrew from coinexchange and now it's on the b3 blockchain stuck. My desktop wallet has synched already and it shows the money is there on the blockchain but nothing on the wallet. there are confirmations still going. Please help

**Comment by AltFreq** [comment]
Your wallet is likely on the wrong chain or not correctly synced. Does your latest block hash match the block Explorer hash

**Comment by MrKowi** [comment]
I am having the same problem. I downloaded the latest wallet from the B3 website and moved the coin from coinexchange but nothing is showing up on wallet but exchange shows the it has been processed.

**Comment by robertorange949** [comment]
the block height for my desktop wallet is at 89697 and the clockchain says it's at block 88697. How do I get the 2 to work?

**Comment by AltFreq** [comment]
Did you download the latest version from here or from b3coin.net? B3coin.net had an old version im pretty sure. Visit the discord wallet-help channel for more help in syncing https://discord.gg/vtRHCA

**Comment by MrKowi** [comment]
Got it! Thank you. 

Go to B3 wallet website and download most recent Wallet. 
Go to bottom left of the screen and click search.
type %appdata% and move to the folder. 
look for 'B3-Coin' folder, open it
Delete everything other than wallet.dat
Run downloaded wallet and wait until it synchronizes.
The transfer should show up. :)

**Comment by amirali22** [comment]
i have same problem,have you guys received your coins?! if yes please give me an advice on IOS,,,i read MrK0wi comment,,,but if he can explain that on Mac-IOS with more detail  i would be grateful ,,,please anyone has received coins update others thank you

**Comment by TommyHeyHey** [comment]
I have the same problem.  Moved 150 kb3 to my b3 wallet: https://chainz.cryptoid.info/b3/tx.dws?307927.htm but it doesn't show up in my wallet

Shows transaction complete on the blockchain explorer.  B3 wallet has synced passed the block my transaction was in.  But a note that the B3 wallet always seems to be 100 blocks behind then current block shown in the B3 explorer...?  Is something wrong with my wallet?  I have the latest version 3.1.1.2.

Was it ok to transfer kb3 to my b3 wallet?  Why can't I see the coins in my wallet?

**Comment by DavidRCameron** [comment]
Patience.... This entire digital system is not error free yet. Neither is
this programming, obviously. The risk to reward is obviously HIGH because
of this ecosystem's situation. It might not be what I just described, there
is another problem existing, I know some new tokens all over the networks
are taking days to issue after the close of an IO. Looks like the mining
network community has to grow in relationship to new companies, human
users, and then tokens x tokens x tokens .... This ecosystem is still 3
years out on growth. My thoughts, I'm not looking for any Quick get
Rich..NOPE, be smart and think year 2022. Take your time, acquire your
stake, even though you miss out on some bonuses, I'd rather miss out for a
few weeks, than loose my money over thinking I don't have to work next
month. There are going to be soooooo many errors and people loosing money
by not being extremely patient and careful. My hats are off to all that do
take that risk and make head way for the rest of us. I do want to say again
Thanks to those early people carving the way !!!

**Comment by despotak** [comment]
@robertorange949 I see on the explorer that the 244.2780225 kB3 was redeemed, so I suspect that you finally saw your coins.

In general, if the transaction is showing on the explorer, but you cannot see it on your wallet, it means that there is some problem with the syncing of your wallet. Please make sure that you use the latest version of the wallet (on the time of the writing is v3.1.1.2) that you can find at  https://github.com/B3-Coin/B3-CoinV2/releases/latest . 

If your wallet shows a different block height than the explorer, please try a full resync (check @MrKowi answer above). If the balance is still incorrect, try the steps at https://github.com/B3-Coin/B3-CoinV2/wiki/How-To:-Rectify-your-incorrect-balance .

@amirali22 Instead of `%appdata%` (which is for windows), you should look at `~/Library/Application Support/B3-CoinV2` since you are using a Mac.

@TommyHeyHey No, there is no problem sending B3 or kB3 on your wallet, since they are equivalent. Please check https://b3coin.io/#kB3 for a quick explanation of what kB3 is.

Since this is a syncing issue, discord is a better place to ask for help. Join us at https://discordapp.com/invite/ARpuv79

This issue is marked for closing and will remain open until 02/02/2018.
