### ISSUE TITLE
Most sends to wallet do not show up - but transactions visible on blockchain

### ISSUE THREAD

**Issue by czarofparadise** [B3-Coin/B3-CoinV2#66]
On Windows 10 platform, both v3.1.2.0 and v3.1.2.2 - 
- I have sent 4 times from coinexchange to the same wallet address
- the first deposit never showed up in the wallet, but shows on the blockchain
- the second deposit never showed up in the wallet, but shows on the blockchain
- the third deposit DID show up in the wallet (and shows on the blockchain)
- the fourth deposit never showed up in the wallet, but shows on the blockchain.

I have uninstalled/reinstalled (reimporting my keys each time).  I was hopeful v3.1.2.2 would resolve the issue, but it did not.  The wallet has always synchronized and appears happy...it just will not display the tokens i've deposited.

Please advise.

**Comment by Kdog3** [comment]
Czarofparadise -- please try the following steps: 
- go to help/debug/console - type in "repairwallet" (no quotes) 
- if it finds something to repair, then restart the wallet.  
- if it does not find anything to repair, then in the existing wallet you have, where the key has been imported ... 
- delete everything from your appdata/roaming/b3coin-v2 folder OTHER than your wallet.dat.  
- go to your downloads folder and double-click the 3.1.2.2 exe - let it sync/load.

**Comment by igoraguillar** [comment]
I have been facing the same problem. 

I sent a email for coinexchange and received this answer:

Hi Igor Aguillar,

This withdrawal has been successfully processed and has been confirmed on the blockchain.

https://chainz.cryptoid.info/b3/tx.dws?1acf69c6e39f6ebd6ba56e48d9bfdba3a05c3a1aae435eade935e27097023ae0.htm

This verifies that the withdrawal had no issue on our end of the transaction. 

If you continue to have a problem receiving the funds you will need to contact support from the other end of the transaction.

On certain Bitcoin based blockchains, you may notice “Not Yet Redeemed” as the transaction status.

This means that the transaction is complete, but has not been used as input for another transaction.

Your coins have been received but not yet spent.

Update and sync your wallet in order to see the coins reflected correctly.

Sincerely,

CoinExchange.io Support Team

Could you guys help me
