### ISSUE TITLE
Wallet crashes when processing a transacation

### ISSUE THREAD

**Issue by tommyranger** [B3-Coin/B3-CoinV2#71]
Hi, my Windows wallet v.3.1.2.2 crashes each time I attempt a 'send' transaction. I can confirm that the wallet is up to date and fully synced. Here is a screenshot of the error message:

![image](https://user-images.githubusercontent.com/36209208/44955918-539d5900-aeb3-11e8-833e-10818c79d9bd.png)

Would be grateful for any assistance on this issue.

Thanks
Tom

**Comment by AltFreq07** [comment]
Your database has been corrupted usually due to a bad shutdown and you now require a full resync.
Close the wallet. 
Head to your B3 coin folder found in %appdata% and remove all files except your wallet.dat. 
Download the bootstrap from the releases section here and extract to the B3 folder.
Reopen wallet and wait for synchronisation. 

For Moe detailed instructions or assistance head to the discord channel
